### ISSUE TITLE
SQL Error's

### ISSUE THREAD

**Issue by ghost** [TerranUlm/MyBB-Plugin-Teamspeak3-Sync#10]
When trying to install and use this plugin I am receiving some SQL errors. When I try to add a server group to a forum group and save the changes this error comes up: 
MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'uf.,uf. FROM mybb_userfields as uf JOIN mybb_users as u ON uf.ufid=u.uid WHERE (' at line 1
Query:
select uf.ufid,u.username,u.usergroup,u.additionalgroups,uf.,uf.,uf. FROM mybb_userfields as uf JOIN mybb_users as u ON uf.ufid=u.uid WHERE (uf. IS NOT NULL OR uf. IS NOT NULL OR uf. IS NOT NULL) AND (uf. != '' OR uf. != '' OR uf. != '')

And when I try to install the plugin, this error comes up:

MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1364 - Field 'regex' doesn't have a default value
Query:
INSERT INTO mybb_profilefields (`name`,`description`,`disporder`,`type`,`length`,`maxlength`,`required`,`viewableby`,`editableby`) VALUES ('TeamspeakID 1','Unique TeamSpeak ID, see "Settings->Identities->Default->Unique ID"',7,'text',70,60,0,'-1','-1')

How can I fix this?

**Comment by TerranUlm** [comment]
What MyBB version are you using? The plugin was created for 1.6.x versions of MyBB. I'd tested it with MyBB 1.8.x but it seams like I never tested reinstalling on 1.8.x. The "regex" column has indeed no default value, but that is an easy fix, just modify the code and and the "regex" line.

```
		$new_profile_field = array(
			"name" => 'TeamspeakID '.$i,
			"description" => 'Unique TeamSpeak ID, see "Settings->Identities->Default->Unique ID"',
			"disporder" => 6+$i,
			"type" => 'text',
			"length" => intval('70'),
			"maxlength" => intval('60'),
			"required" => intval('0'),
			"viewableby" => '-1',
			"regex" => '',
			"editableby" => '-1'
		);
```


The other problem seams related to that. Could you try it and report back to me?

**Comment by ghost** [comment]
Thank you, that fixed everything, how often is the server checked to see if users need to be updated with different permissions?

**Comment by TerranUlm** [comment]
The script is run bei a MyBB task about every 30 minutes or when a forum group is edited. Or you can run it manually by starting the task in the forum admin panel.

**Comment by ghost** [comment]
I have tried to change it in the task manager to a '*' as it says to make it run every minute but that does not seem to work, I have also tried making it every 5 minutes and the task manager says it should run but it does not seem to be running. Any ideas why?

**Comment by TerranUlm** [comment]
There are several methods to debug that issue. You should enable "show serverquery accounts" (or something likt that, I have no TS client in the office) in the server favorites settings for your server.  Whenever the server runs the script you should see your serverquery account connecting.
Another method is the logfile which should be in the cache folder of the forum (teamspeak3_log.php).

Btw.: as you have reinstalled the plugin - have you redone all settings? Uninstalling the plugin whipes everything...

**Comment by TerranUlm** [comment]
You shouldn't run the script that often for production use, as it puts a lot of load and stress on both the forum and the TS server.

**Comment by ghost** [comment]
I can manually run it if I click the settings icon and then run, but it does not seem to run every minute, maybe I'll change it to every 10 minutes and see if that helps

**Comment by TerranUlm** [comment]
Someone needs to open pages in the forum so the task scheduler is executed, that is by the design of MyBB, there is no independent process running in the background, everything happens within the webserver.

**Comment by ghost** [comment]
Do you know if I could create a cron task to run the teamspeak3.php without having the webserver running?

**Comment by TerranUlm** [comment]
Sure, just use "wget" or "curl" etc. and open your forum, that should do the trick.
