### ISSUE TITLE
Factory Errors nach after Re-Install

### ISSUE THREAD

**Issue by zany8892** [TerranUlm/MyBB-Plugin-Teamspeak3-Sync#11]
Ive just re installed the Plugin, and only recieve this error : 

TeamSpeak3::factory: Error 1540: convert error

**Comment by zany8892** [comment]
So do you have an Idea why this happens ? We really need to figure it out...

**Comment by TerranUlm** [comment]
That problem is not directly releated to the plugin but to the TS3 PHP Library. I cannot nail it down exactly but you should check all your settings for the plugin, especially for empty entries as the error message should output something after "covert error".

**Comment by TerranUlm** [comment]
Closing issue due to lack of feedback.
