### ISSUE TITLE
Not connecting to server

### ISSUE THREAD

**Issue by ghost** [TerranUlm/MyBB-Plugin-Teamspeak3-Sync#12]
Hi,

All of a sudden the plugin doesnt seem to want to connect to my server, I have changed no settings and I have done nothing since this happens, in the log it says that it executes the task but there is no query connecting to my server.

Thanks

**Comment by TerranUlm** [comment]
Hi HCStrike,
you should check your settings, maybe something got corrupted (not related to the plugin). Is your TS on the same host then your forum? If not, check your firewall settings too.

**Comment by hcphoon01** [comment]
Like I said before, I have not changed anything, the plugin connects every so often but not every 5 minutes like I have set it to. Even if I manually run the task in myBB it doesn't always connect

**Comment by TerranUlm** [comment]
OK, I need to find a glass sphere. You say that it works at least sometimes but not always. I have no idea about your setup. On which host is the forum located? Where is the TS located? Same host or at least the same datacenter? The reason for your issues might be located in the way your systems are set up. Maybe the network connection between the systems is locking up occasionally for whatever reason. So tell me more about your setup.

**Comment by ghost** [comment]
Sorry about the multiple accounts, my forum and TS server are on the exact same VPS hosted by digital ocean

**Comment by ghost** [comment]
I get this error in my syslog every 5 mins 
`Aug 29 07:10:29 MultiCrew php[2580]: PHP Fatal error:  Uncaught Error: Call to undefined function utf8_encode() in /var/www/forums/TeamSpeak3/Helper/String.php:475
Aug 29 07:10:29 MultiCrew php[2580]: Stack trace:
Aug 29 07:10:29 MultiCrew php[2580]: #0 /var/www/forums/TeamSpeak3/Adapter/ServerQuery.php(205): TeamSpeak3_Helper_String->toUtf8()
Aug 29 07:10:29 MultiCrew php[2580]: #1 /var/www/forums/TeamSpeak3/Node/Abstract.php(85): TeamSpeak3_Adapter_ServerQuery->prepare('login', Array)
Aug 29 07:10:29 MultiCrew php[2580]: #2 /var/www/forums/TeamSpeak3/Node/Abstract.php(97): TeamSpeak3_Node_Abstract->prepare('login', Array)
Aug 29 07:10:29 MultiCrew php[2580]: #3 /var/www/forums/TeamSpeak3/Node/Host.php(839): TeamSpeak3_Node_Abstract->execute('login', Array)
Aug 29 07:10:29 MultiCrew php[2580]: #4 /var/www/forums/TeamSpeak3/TeamSpeak3.php(330): TeamSpeak3_Node_Host->login(Object(TeamSpeak3_Helper_String), Object(TeamSpeak3_Helper_String))
Aug 29 07:10:29 MultiCrew php[2580]: #5 /var/www/forums/inc/plugins/teamspeak3.php(367): TeamSpeak3::factory(Object(TeamSpeak3_Helper_Uri))
Aug 29 07:10:29 MultiCrew php[2580]: #6 /var/www/forums/inc/tasks/teamspeak3.php(31): teamspeak3_connect()
Aug 29 07:10:29 MultiCrew php[2580]: #7 /var/www/forums/inc/functions_task.php(88): task_teamspeak3(Array)
Aug 29 07:10:29 MultiCrew php[2580]: #8 /var/www/forums/task.php(50): run_task()
Aug 29 07:10:29 MultiCrew php[2580]: #9 {main}
Aug 29 07:10:29 MultiCrew php[2580]:   thrown in /var/www/forums/TeamSpeak3/Helper/String.php on line 475`

**Comment by TerranUlm** [comment]
Sorry for the late response:
That error is not an error of the plugin or the TS library but instead of PHP7 itself. Read the following post to solve the issue:
https://stackoverflow.com/questions/35701730/utf8-endecode-removed-from-php7

**Comment by TerranUlm** [comment]
no further update received @ghost so I'm closing the issue.
