### ISSUE TITLE
Ts3 Query connects and instant timeout without setting Group

### ISSUE THREAD

**Issue by PB-Lesco** [TerranUlm/MyBB-Plugin-Teamspeak3-Sync#13]
<13:40:08> "Unknown from 127.0.0.2:37785" loggte sich in Channel "[cspacer]╠════════Eingangshalle════════╣" ein
<13:40:08> "Unknown from 127.0.0.1:54597" loggte sich in Channel "[cspacer]╠════════Eingangshalle════════╣" ein
<13:40:08> "Unknown from 127.0.0.1:59587" loggte sich in Channel "[cspacer]╠════════Eingangshalle════════╣" ein
<13:40:09> Die Verbindung von "Unknown from 127.0.0.1:54597" wurde unterbrochen (connection lost)
<13:40:09> Die Verbindung von "Unknown from 127.0.0.1:37785" wurde unterbrochen (connection lost)
<13:40:09> Die Verbindung von "Unknown from 127.0.0.1:59587" wurde unterbrochen (connection lost)

**Comment by TerranUlm** [comment]
Editiere doch mal Deine IP Adresse aus dem Logfile, das ist ja die reinste Einladung für böse Buben ;)

Das sieht aber eher nicht nach dem Sync Plugin aus, diese Einträge, denn dieses meldet sich ja am TS Server an, ist also nicht "Unknown". Bei mir sieht das im TS Server Logfile so aus:
`2018-01-31 10:21:44.716628|INFO    |VirtualServer |1  |query client connected 'OPT-C Forum Rechte Sync from 127.0.0.1:55244'(id:7)`
Oder Du hast falsche Logindaten in den Settings eingetragen oder den Account falsch im TS angelegt.

**Comment by TerranUlm** [comment]
Mangels Feedback schließe ich das Issue.
