### ISSUE TITLE
Group not being given

### ISSUE THREAD

**Issue by nobodyshome** [TerranUlm/MyBB-Plugin-Teamspeak3-Sync#15]
I have set up both the group and Teamspeak plugin, can confirm it connects to the server. However, it never assigns groups to people. If anything is needed let me know, and ill supply what I can.

**Comment by TerranUlm** [comment]
You should check the logfile of the plugin, it is located in the cache folder of the forum.

**Comment by TerranUlm** [comment]
no further update received @nobodyshome so I'm closing the issue.
