### ISSUE TITLE
Multiple TS

### ISSUE THREAD

**Issue by MichkaPe** [TerranUlm/MyBB-Plugin-Teamspeak3-Sync#17]
Hello,
I have 2 TS.
Is it possible to "install this addon 2 time" and have 2 differents configurations?

**Comment by TerranUlm** [comment]
Well, you would have to make a full copy of the plugin and rename all the function names to match the new plugin name. Also edit the content of the teamspeak3_info function. And the table names and columns as well.
It is doable but you should know what you are doing...

**Comment by MichkaPe** [comment]
ok thank i'll try on my crash test mybb forum :)

**Comment by Mrkiklick** [comment]
ok that worked!! is it possible to add multiple servergroup and a channelgroup il more than one channel?
