### ISSUE TITLE
Not removing group

### ISSUE THREAD

**Issue by sfkandersen** [TerranUlm/MyBB-Plugin-Teamspeak3-Sync#18]
Hey, so the plugins work just fine when adding people to the desired group, however, when I am trying to remove them from the group it seems that the website does not resync with the teamspeak server and therefor the teamspeak groups stay on the person while it disappears from the person on the website.

**Comment by TerranUlm** [comment]
Hey @sfkandersen , nice to read that the plugin works mostly for your installation.
Most probably that is a permissions problem but to be sure we need to look into the logfile.
You can find that logfile in the "cache" subfolder of the forum, its name is "teamspeak3_log.php".

**Comment by sfkandersen** [comment]
Yeah checked that already, but here you go.
[teamspeak3_log.txt](https://github.com/TerranUlm/MyBB-Plugin-Teamspeak3-Sync/files/3401599/teamspeak3_log.txt)

**Comment by TerranUlm** [comment]
The first log entry "`TeamSpeak3::factory: Error 1540: convert error`" indicates an configuration error in the forum settings for the plugin, also see issue #11

I had that problem almost exactly one year ago on July 16th 2018 after a upgrading my forum to a newer version.

**Comment by sfkandersen** [comment]
Fixed that error, that error came up earlier when i couldnt add people, but it seems no error shows up when removing people again

**Comment by sfkandersen** [comment]
Update to this, it seems that it only revokes the teamspeak tag, IF i go back into the forum group setting of the desired group and hit save.

So for it to work i would have to:

Assign user on the forum ie. Senior Admin
Go into the usergroup Senior Admin and hit save
And then it would update the teamspeak tag

EDIT:
It seems that you have to manually force it to recheck the groups either hitting save in the usergroup settings or in the usercp settings

**Comment by TerranUlm** [comment]
Sorry for the late response. 

There are several events the plugin responds to. Some reactions are immediately, others are scheduled.
Changes done by an admin should happen immediately, user actions are delayed up to 30 minutes. The reason for that is to reduce the load of the webserver as some functions are very time consuming.
At my forum only admins and some plugins can assign usergroups, I never tested any other way of assigning a group to a user. But that shouldn't matter, as the sync happens about every 30 minutes and should catch up all usergroup changes.
You can run the update task manually in the admin pannels Task Manager.
