### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by de-Rick** [TerranUlm/MyBB-Plugin-Teamspeak3-Sync#3]
Hello,

I get a SQL-Error when I try to install your Plugin.

URL: king-gaming.de
Style: duende
Plugins: Teamspeak 3 Group Sync, (TS3PHPFramework in the ROOT-Folder of mybb)
MyBB: 1.8.7
PHP: 5.6.22-0+deb8u1
SQL: MySQL 5.5.5

MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
    1054 - Unknown column 'editable' in 'field list'
Query:
    INSERT INTO mybb_profilefields (`name`,`description`,`disporder`,`type`,`length`,`maxlength`,`required`,`editable`,`hidden`,`postnum`) VALUES ('TeamspeakID 1','eindeutige Teamspeak ID, zu finden unter "Einstellungen->Identitäten->Standard->Eindeutige ID"',7,'text',70,60,0,1,0,0) 

Kind regards,

Rick

**Comment by TerranUlm** [comment]
Hi Rick,

please download the latest release 1.2.0 which includes a lot of fixes for MyBB 1.8.x related issues, including your reported SQL error.

Terran

**Comment by de-Rick** [comment]
Worked :) Danke für deine Arbeit
