### ISSUE TITLE
Stop this plugin removing groups added by TeamSpeak clients

### ISSUE THREAD

**Issue by ssamjh** [TerranUlm/MyBB-Plugin-Teamspeak3-Sync#4]
We have noticed that this plugin removes the group from people whom we give it to manually.

Is there a work around for this?

**Comment by TerranUlm** [comment]
No, that is an intended behaviour of the plugin. It syncs the forum permissions to TS3. If you add user to the forum group, the user will also get added to the TS3 group (according to your configuration), but only if the user has added his unique TS3 ID to the user profile fields.
If you remove that user from the forum group, he will also be removed from the TS3 group.
So you cannot manually add users to the TS3 group directly, you always have to add them to the forum group and make sure they have the TS3 unique ID in their profile fields.
As an administrator you can add the ID for them.
