### ISSUE TITLE
Framework Not Found

### ISSUE THREAD

**Issue by PaXo0** [TerranUlm/MyBB-Plugin-Teamspeak3-Sync#6]
TeamSpeak 3 PHP Framework not found, please specify the path in the 'TeamSpeak 3 Group Sync plugin' settings

**Comment by PaXo0** [comment]
The link to the ts3 framework is broken

**Comment by TerranUlm** [comment]
Updated the link to the framework. Seams like teamspeak.org changed the entire download section, almost everything is gone...

**Comment by PaXo0** [comment]
I have managed to get the website part of it working and done all the instructions but it is not allowing me to create a server query account and connect to it sucessfully
