### ISSUE TITLE
Plugin Does Not Connect to my server

### ISSUE THREAD

**Issue by PaXo0** [TerranUlm/MyBB-Plugin-Teamspeak3-Sync#7]
when i type in my serverquery login into the plugin homepage area where you fill in all the details ( all correct ) it dose not connect to the server idk why i have tired it myself though localhost ect but dose not work any ideas

**Comment by TerranUlm** [comment]
The plugin writes a logfile to the "cache" subfolder of the forum. You might be able to find the reason why it doesn't connect to the TS3 server.

**Comment by PaXo0** [comment]
thanks

**Comment by PaXo0** [comment]
i have tried reinstalling and changeing it in the settings.php aswell seeing if it works

**Comment by PaXo0** [comment]
it goes to this then saids 404 not found

http://protected.com/forums/admin/index.php?module=config-settings&action=change

**Comment by PaXo0** [comment]
error 110 but all ports open ect

**Comment by TerranUlm** [comment]
Sorry, somehow I didn't get any update mails about this issue...

Is "protected.com" your website or just a placeholder? As there is no forum at protected.com/forum ...

**Comment by PaXo0** [comment]
Ah sorry about that i really diddent have time with exams ect - it is the host blocking the server from connecting to the outside world apart from the 80 or 8080 port
